version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db-prueba
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dinosaurio1724
      MYSQL_DATABASE: prueba_api
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pDinosaurio1724"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  api-prueba:
    build: .
    container_name: api-prueba
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:Dinosaurio1724@db:3306/prueba_api
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

volumes:
  mysql_data:
